### ISSUE TITLE
DBTC sometimes not able to query account id for no particular reason

### ISSUE THREAD

**Issue by niharikay** [dpguthrie/dbtc#71]
We have seen blips with DBTC api when running different functions like - listing all jobs. Here is an example when calling the API from CircleCI.
<img width="1021" alt="Screenshot 2023-02-02 at 1 23 48 PM" src="https://user-images.githubusercontent.com/43078333/216689975-52729393-60f6-4e0c-89d9-3abf7c8eefb2.png">

**Comment by dpguthrie** [comment]
Yeah, this error needs to be handled better.  I'm not entirely sure what's happening here but part of the problem may be using the `list_runs_v4` endpoint.  This will be deprecated soon so I would recommend moving to `list_runs`.  This endpoint was updated in the most recent version (0.3.4) to include some additional arguments:

- job_definition_id
- environment_id
- project_id
- deferring_run_id
- status
- order_by
- offset
- limit

**Comment by niharikay** [comment]
Thanks @dpguthrie
