### ISSUE TITLE
Dependency Error?

### ISSUE THREAD

**Issue by jschintz-windriver** [dpguthrie/dbtc#87]
Hi Doug!

I started to get an error consistently when using the package late yesterday.

```
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

It looks like your streamlit app is throwing the same error.  
https://dpguthrie-dbtc-streamlit-home-yy7c0b.streamlit.app/

I tried playing around with the dependecy versions, but have had no luck yet.

Btw, I've enjoyed using the package to date, the app and the documention.  Really appreciate the work you put into this.

**Comment by wbaker23** [comment]
I am getting the same issue.

**Comment by jschintz-windriver** [comment]
The internet seems to think pydantic is the troublemaker.
Hotfix was released a couple of hours ago
https://github.com/pydantic/pydantic/releases/tag/v1.10.8
